server:
  port: 8080


#数据库配置
druid:
  datasource:
    user:
      master:
        url: jdbc:mysql://localhost:3306/lcy?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
      slave:
        url: jdbc:mysql://localhost:3306/lcy?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root

logging:
  config: classpath:log4j2.yml
spring:
  application:
    name: sso-server